title: Vaibhav Yenamandra's Blog
languageCode: en-us
defaultContentLanguage: en
baseURL: 'https://calloc.net/'
theme: xmin
math: true
params:
  favicon: favicon.ico
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about
      weight: 2
    - name: Résumé
      url: /resume.pdf
      weight: 3

markup:
  highlight:
    codeFences: true
    style: friendly
  goldmark:
    renderer:
      unsafe: true
